name: Update README.md

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name salteadorneo
        git config user.email hola@salteadorneo.dev
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Test workflows"
        git push origin master
